import Products from "@/components/Products"
import getQueryClient from "@/components/providers/getQueryClient"
import { dehydrate } from "@tanstack/react-query"
import Hydrate from "@/components/providers/HydrateClient"
import { getProducts } from "@/services/productApi"
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Home - shadcnext',
  description: 'Generated by create next app',
}

export default async function Home() {
  const session = await getServerSession()
  const queryClient = getQueryClient()
  await queryClient.prefetchQuery(["products"], getProducts)
  const dehydratedState = dehydrate(queryClient)

  if(!session){
    redirect("/signin")
  }

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-4 ">
      <Hydrate state={dehydratedState}>
        <Products />
      </Hydrate>
    </main>
  )
}